version: '3'
services:
  # jenkins:
  #   build: 
  #     context: ./jenkins      
  #   container_name: jenkins
  #   environment:
  #     - JENKINS_HOME=/opt/jenkins/home
  #   volumes:
  #     - ./jenkins/data:/opt/jenkins/home
  #   ports:
  #     - "50000:50000"
  #     - "8080:8080"      
  sonarqube:
    image: sonarqube:alpine
    container_name: sonarqube
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"
      - "9001:9001"
  was:
    image: ibmcom/websphere-traditional
    container_name: was
    volumes:
      - ./was/tmp/PASSWORD:/tmp/PASSWORD
    ports:
      - "9043:9043"
      - "9443:9443"