/*
properties([
    parameters([
        gitParameter(branch: '',
                     branchFilter: 'origin/(.*)',
                     defaultValue: 'master',
                     description: '',
                     name: 'BRANCH',
                     quickFilterEnabled: false,
                     selectedValue: 'NONE',
                     sortMode: 'NONE',
                     tagFilter: '*',
                     type: 'PT_BRANCH')
    ])
])
*/
node {
    stage('scm'){
        checkout scm
        //git branch: "${params.BRANCH}", url: 'https://gitlab.com/codilabs/Ear-Test.git'
    }

    stage('sonarqube'){
        withSonarQubeEnv() {
            sh "sonarscanner"
            steps {
                waitForQualityGate abortPipeline: true
            }
        }        
    }   

    stage('build'){
        withMaven() {
            sh "mvn clean package -target 1.8 -source 1.8"
        }
    } 

    stage('deploy'){

    }

    stage('notify'){
        emailtext (
            subject: "Job ${env.JOB_NAME} ${env.BUILD_NUMBER}",
            body: "Check output ${env.BUILD_URL}",
            to: "test@test.com"
        )     
    }
}